// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/motemen/example-gomock-ill-formatted-message (interfaces: Foo)

// Package eg is a generated GoMock package.
package eg

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFoo is a mock of Foo interface.
type MockFoo struct {
	ctrl     *gomock.Controller
	recorder *MockFooMockRecorder
}

// MockFooMockRecorder is the mock recorder for MockFoo.
type MockFooMockRecorder struct {
	mock *MockFoo
}

// NewMockFoo creates a new mock instance.
func NewMockFoo(ctrl *gomock.Controller) *MockFoo {
	mock := &MockFoo{ctrl: ctrl}
	mock.recorder = &MockFooMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoo) EXPECT() *MockFooMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MockFoo) Foo(arg0 interface{}) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Foo", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// Foo indicates an expected call of Foo.
func (mr *MockFooMockRecorder) Foo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MockFoo)(nil).Foo), arg0)
}
